### ISSUE TITLE
Inconsistency between Bigdecimal 3.0.x and 3.1.x

### ISSUE THREAD

**Issue by guillaumebriday-pa** [ruby/bigdecimal#244] opened 2022-12-03 02:25 UTC
Whenever I try to upgrade from Ruby 3.x to Ruby 3.1, it also updates the gem Bigdecimal from `3.0.x` to `3.1.x` and this leads to inconsistency when I retrieve a decimal column with Rails 

As you can see on these screenshots, the decimal precision changes between the two versions.

Do you know why? And how to fix it?

As workaround, I added this line to my Gemfile:

```ruby
gem 'bigdecimal', '< 3.1'
```

And it works back again

<img width="437" alt="Screenshot 2022-12-02 at 20 44 20" src="https://user-images.githubusercontent.com/89008587/205417130-e74612e0-d30e-487a-b5ba-7e7fd648c9e4.png">
<img width="442" alt="Screenshot 2022-12-02 at 20 44 54" src="https://user-images.githubusercontent.com/89008587/205417132-6804cb3c-a64b-4fc4-b0f6-77e0eb93bfc3.png">

thank you in advance

**Comment by wheresrobert** [comment] 2022-12-22 00:01
I don't have a fix for this, but I can confirm this does happen to me as well. We are trying to update from Ruby 2.7 to 3.1 and we tests fail due to an unexpected increase in precision that was previously not there. Dropping to 3.0.2 gets the results back to what we expect.

**Comment by mrkn** [comment] 2023-02-20 14:42
Could you please describe more detailed information?  I cannot investigate the issue you encountered because I don't know what are `other_budget`, `amounts_lines`, and `ratio_base`.

**Comment by thorstenspringhart** [comment] 2023-03-19 11:47
We have the same issue with a simple unit conversion:

Before the upgrade we had the following result:

```
0> value = BigDecimal('64')
=> 0.64e2
0> result = (value -32)* 5 /9 +273.15
=> 0.290927777777777777778e3
0> result.to_s
=> "290.927777777777777778"
```

After the upgrade
```
0> value = BigDecimal('64')
=> 0.64e2
0> result = (value -32)* 5 /9 +273.15
=> 0.290927777777777777777777777777777777778e3
0> result.to_s
=> "290.927777777777777777777777777777777778"
```

**Comment by mrkn** [comment] 2023-03-19 13:07
@thorstenspringhart BigDecimal does not preserve the result precision of `BigDecimal#/` among the different versions.  In recent change, we increased the result precision of `BigDecimal#/` for the case of infinite decimals.  If you need to control the precision of division, you must use `BigDecimal#div` instead of `BigDecimal#/`.

**Closed** 2023-04-08 18:52 UTC
Labels: wontfix
