### ISSUE TITLE
Error Updating Under Win 10 x64

### ISSUE THREAD

**Issue by tajmone** [ruby/bigdecimal#122] opened 2018-12-25 10:21 UTC
(hopefully not a duplicate #118 and #119, since this is make-related error)

    ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]

When I try to update the gem under Win 10 x64 I get this error:

```
current directory: C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bigdecimal-1.4.1/ext/bigdecimal/util
C:/tools/ruby25/bin/ruby.exe -r ./siteconf20181225-9440-zwbdav.rb extconf.rb
checking for Windows... yes
creating Makefile

current directory: C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bigdecimal-1.4.1/ext/bigdecimal/util
make "DESTDIR=" clean
bash.exe: warning: could not find /tmp, please create!

current directory: C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bigdecimal-1.4.1/ext/bigdecimal/util
make "DESTDIR="
generating util-x64-mingw32.def
bash.exe: warning: could not find /tmp, please create!
compiling util.c
linking shared-object bigdecimal/util.so
x86_64-w64-mingw32-gcc.exe: error: C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bigdecimal-1.4.1/tmp/x64-mingw32/bigdecimal/2.5.3/bigdecimal.so: No such file or directory
make: *** [Makefile:259: util.so] Error 1

make failed, exit code 2
```

**Comment by mrkn** [comment] 2018-12-25 11:46
This is not a duplicate of #118 and #119.
Please tell me how to make reproducible environment.

**Closed** 2018-12-26 01:41 UTC

**Comment by mrkn** [comment] 2018-12-26 02:16
@tajmone Please use version 1.4.2.
